plugins {
    id 'java-library'
    id('io.qameta.allure') version '2.12.0'
}

repositories {
    mavenCentral()
}

allure {
    report {
        version.set("2.25.0")
    }
    adapter {
        aspectjWeaver.set(true)
        frameworks {
            junit5 {
                adapterVersion.set("2.25.0")
            }
        }
    }
}

dependencies {
    testImplementation(
            "org.junit.jupiter:junit-jupiter:5.10.0",
            'org.slf4j:slf4j-simple:2.0.9',
            "io.qameta.allure:allure-selenide:2.25.0",
            'io.qameta.allure:allure-junit5:2.25.0',
            'org.seleniumhq.selenium:selenium-java:4.18.1',
            'com.github.javafaker:javafaker:1.0.2',
            'com.codeborne:selenide:7.2.3'
    )
    testImplementation 'io.netty:netty-all:4.1.104.Final'
}

tasks.withType(Test) {
    useJUnitPlatform()
    systemProperties(System.getProperties())

    testLogging {
        lifecycle {
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }
}

test {
    useJUnitPlatform()
}


task Positive_test(type: Test) {
    useJUnitPlatform {
        includeTags("Positive")
    }
}

task Negative_test(type: Test) {
    useJUnitPlatform {
        includeTags("Negative")
    }
}

task Regression_test(type: Test) {
    useJUnitPlatform {
        includeTags("Regression")
    }
}

task All_test(type: Test) {
    useJUnitPlatform {
        includeTags("All")
    }
}

task web_test(type: Test) {
    useJUnitPlatform {
        includeTags("web")
    }
}

task logo_test(type: Test) {
    useJUnitPlatform {
        includeTags("logo")
    }
}

task categories_test(type: Test) {
    useJUnitPlatform {
        includeTags("categories")
    }
}

task search_test(type: Test) {
    useJUnitPlatform {
        includeTags("search")
    }
}